### ISSUE TITLE
Checking the log

### ISSUE THREAD

**Issue by overstartup** [JKorf/OKX.Net#12]
How can I check the log in debug mode? In old version, I remember we could set it as parameter in client option.

**Comment by prodigy1** [comment]
You need to pass a ILoggerFactory instance to the constructor of the clients. See this constructor:
https://github.com/JKorf/OKX.Net/blob/main/OKX.Net/Clients/OKXRestClient.cs#L31C48-L31C48

**Comment by JKorf** [comment]
Either that or use dotnet DI to instantiate the client, it's configured according to the dotnet logging configuration then
