### ISSUE TITLE
Missing GET / Algo order details

### ISSUE THREAD

**Issue by dante1989** [JKorf/OKX.Net#15]
**GET / Order details** is OK: https://www.okx.com/docs-v5/en/#order-book-trading-trade-get-order-details
**clientFutureOKX.UnifiedApi.Trading.GetOrderDetailsAsync** is OK

But missing: GET / Algo order details: https://www.okx.com/docs-v5/en/#order-book-trading-algo-trading-get-algo-order-details
i do not see this function in **clientFutureOKX.UnifiedApi.Trading.**

**Comment by JKorf** [comment]
Added in latest version

**Comment by dante1989** [comment]
When i use: dim ItemOrderOKX= clientFutureOKX.UnifiedApi.Trading.GetAlgoOrderAsync(AlgoId)
i got error from ItemOrderOKX.Error.Message: 
**Deserialize JsonSerializationException: Error converting value "" to type 'System.Boolean'. Path 'data[0].amendPxOnTriggerType'**
