### ISSUE TITLE
error from GetAlgoOrderAsync

### ISSUE THREAD

**Issue by dante1989** [JKorf/OKX.Net#18]
When i use: dim ItemOrderOKX= clientFutureOKX.UnifiedApi.Trading.GetAlgoOrderAsync(AlgoId)
i got error from ItemOrderOKX.Error.Message:
**Deserialize JsonSerializationException: Error converting value "" to type 'System.Boolean'. Path 'data[0].amendPxOnTriggerType', line 1, position 187.**

My Type Order is Trigger and State is Live

**Comment by JKorf** [comment]
This should be fixed when using the latest CryptoExchange.Net version, V6.2.5. You can install that version directly until a new version of the OKX library is released with the new package reference

**Comment by dante1989** [comment]
CryptoExchange.Net version, V6.2.5 is ok for this problem
