### ISSUE TITLE
Exception in SetAccountLeverageAsync

### ISSUE THREAD

**Issue by danielhw2** [JKorf/OKX.Net#21]
When I call this code

`ClienteRest.UnifiedApi.Account.SetAccountLeverageAsync(7, OKX.Net.Enums.OKXMarginMode.Isolated).Result;`

It gives me this Exception:

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Either instId or ccy is required; if both are passed, instId will be used by default.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   ...

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: Either instId or ccy is required; if both are passed, instId will be used by default.
```

CryptoExchange.Net  6.2.1
JK.OKX.Net  1.4.3
.NET 8.0

**Comment by JKorf** [comment]
You need to also pass in either the asset or symbol parameter

**Comment by danielhw2** [comment]
My bad... Thank you!

**Comment by danielhw2** [comment]
Hello, thanks for the answer.


I managed to work passing the  symbol parameter, but with the asset it returns this error: 

"Parameter mgnMode error"

The code:

`ClienteRest.UnifiedApi.Account.SetAccountLeverageAsync(7, OKXMarginMode.Isolated, "BTC", null, OKXPositionSide.Long, CancellationToken.None).Result;`

**Comment by danielhw2** [comment]
Ok. I resolved the issue by only using the symbol parameter... Thanks!
