### ISSUE TITLE
error from property TriggerTime in Class OKXAlgoOrder

### ISSUE THREAD

**Issue by dante1989** [JKorf/OKX.Net#23]
When i get order (is **Effective**, **triggered**) from OKXAlgoOrder. The property TriggerTime get Null Value for all Function: GetAlgoOrderAsync, GetAlgoOrderListAsync, GetAlgoOrderHistoryAsync

Please check property TriggerTime 

Thank you so much

**Comment by JKorf** [comment]
It seems to be mapped correctly, could you check if the value is actually returned from the server?

**Comment by dante1989** [comment]
ok, i will check again and tell you soon

**Comment by dante1989** [comment]
This error from OKX's server
It works ok now
