### ISSUE TITLE
Missing endpoint "mass-cancel" (Cancel All orders)

### ISSUE THREAD

**Issue by danielhw2** [JKorf/OKX.Net#27]
Missing this endpoint: https://www.okx.com/docs-v5/en/#spread-trading-rest-api-cancel-all-orders

Can't find this endpoint in `restclient.UnifiedApi.Trading`

CryptoExchange.Net 6.2.5
JK.OKX.Net 1.5.0

**Comment by JKorf** [comment]
That endpoint is part of Spread trading, which isn't supported at all atm. Order book trading doesn't have the same functionality, though it offers a batch cancellation endpoint which is already available.
