### ISSUE TITLE
GetKlinesAsync request with custom dates return empty candles list

### ISSUE THREAD

**Issue by Akunin88** [JKorf/OKX.Net#33]
![1](https://github.com/JKorf/OKX.Net/assets/40500500/db4bf3a9-f694-4797-aca9-d67c64ec4050)

DateTime startTime1 = DateTime.UtcNow.AddDays(-5);
var request = await client.UnifiedApi.ExchangeData.GetKlinesAsync("BTC-USDT", OKX.Net.Enums.OKXPeriod.OneMinute, startTime1, startTime1.AddMinutes(200),  limit: 300);

**Comment by JKorf** [comment]
The GetKlines endpoint only supports that last 1440 entries, so OneMinute klines 5 days ago is too far back.
You can instead use the GetKlineHistoryAsync endpoint, though that has a max limit of 100 results.
