### ISSUE TITLE
property  `Success` is true when GetOrderBookAsync gets an error result

### ISSUE THREAD

**Issue by zgx** [JKorf/OKX.Net#39]
When using the `OKXRestClient.UnifiedApi.ExchangeData.GetOrderBookAsync` method, I found that when the exchange returns an error, the result is misjudged as Success. The behavior I expect is that if the exchange returns an error, then the result should be marked as an error, not success.

Steps to reproduce:  Call `OKXRestClient.UnifiedApi.ExchangeData.GetOrderBookAsync` with any symbol that not exist

I think the error comes from code like below:
```
        if (!result.Success || result.Data.Data.Count() == 0) return result.AsError<OKXOrderBook>(result.Error!);
```

when result.Error is null, the returned result‘s `Success` property will be true.

**Comment by JKorf** [comment]
Hi this check indeed incorrect, fixed it in the latest version
