### ISSUE TITLE
Can you rename OKXTicker.BestAskSize and OKXTicker.BestBidQuantity?

### ISSUE THREAD

**Issue by Tendx** [JKorf/OKX.Net#42]
In class OKXTicker, I found property BestAskSize was mapped on "askSz" and BestBidQuantity was on "bidSz". 
You may make their names same style.

**Comment by JKorf** [comment]
Hi, yes that makes sense, I'll rename it in next version

**Comment by JKorf** [comment]
Fixed in latest version
