### ISSUE TITLE
The JSON value could not be converted to System.Nullable`1[System.Int32]

### ISSUE THREAD

**Issue by dante1989** [JKorf/OKX.Net#48]
After i upgraded to version 2.0.0
I use this function clientOKX.UnifiedApi.Account.GetPositionsAsync
i got error: The JSON value could not be converted to System.Nullable`1[System.Int32]. Path: $ | LineNumber: 0 | BytePositionInLine: 7.
The old version (Version 1.11.1 - 25 Jun 2024) is ok

**Comment by JKorf** [comment]
Do you know what the response was? The Position model itself doesn't have any int properties, so I'm trying to check whhere that error is coming from

**Comment by dante1989** [comment]
When the position is not opened, i got that error

**Comment by dante1989** [comment]
i'm sorry, the error from this Function GetLeverageAsync, not GetPositionsAsync

**Comment by dante1989** [comment]
try

Dim ItemFuturesDonBayOKX = Await clientOKX.UnifiedApi.Account.GetLeverageAsync(Symbol_USDFuture, OKX.Net.Enums.MarginMode.Cross)

Dim DonBayActive_Long = ItemFuturesDonBayOKX.Data(0).Leverage.Value
Dim DonBayActive_Short = ItemFuturesDonBayOKX.Data(1).Leverage.Value

Catch ex As Exception

End Try

ex.Message get error: i got error: The JSON value could not be converted to System.Nullable`1[System.Int32]. Path: $ | LineNumber: 0 | BytePositionInLine: 7.
The old version (Version 1.11.1 - 25 Jun 2024) is ok

**Comment by JKorf** [comment]
Yeah I found the issue, the error response parsing had a bug. I'll fix it and push a new version later today

**Comment by JKorf** [comment]
I can't push a new package at the moment unfortunately due to an issue with nuget, but will do so when I can.

**Comment by dante1989** [comment]
thank you so much

**Comment by dante1989** [comment]
After i upgraded to version 2.1.0
i got the new error
ex.Message get error: Value cannot be null.
Parameter name: source
ItemFuturesDonBayOKX.Error.Message got the error: mgnMode cannot be empty

**Comment by JKorf** [comment]
Fixed in the latest version
