### ISSUE TITLE
Underlying requirement for GetOpenInterestsAsync call

### ISSUE THREAD

**Issue by badokun** [JKorf/OKX.Net#54]
https://github.com/JKorf/OKX.Net/blob/32822c284269802c796d3ca540bbc169412f9507/OKX.Net/Clients/UnifiedApi/OKXRestClientUnifiedApiExchangeData.cs#L356

This is incorrect. 

```
  if (instrumentType == InstrumentType.Swap && string.IsNullOrEmpty(underlying))
            throw new ArgumentException("Underlying is required for Option.");
```

When supplying an InstrumentType.Swap it should not throw.

**Comment by JKorf** [comment]
Has been fixed in the latest version
