### ISSUE TITLE
GetTickersAsync Error

### ISSUE THREAD

**Issue by overstartup** [JKorf/OKX.Net#6]
This method return error, I'm using it is demo environment         
`       var result = okxRestClient.UnifiedApi.ExchangeData.GetTickersAsync(OKXInstrumentType.Swap).Result;`

`Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'data[52].bidPx', line 1, position 15871.`

**Comment by JKorf** [comment]
Thanks for the report, fixed in latest version
