### ISSUE TITLE
GetSymbolsAsync error

### ISSUE THREAD

**Issue by overstartup** [JKorf/OKX.Net#7]
This method return error, I'm using it is demo environment .
`  var result = okxRestClient.UnifiedApi.ExchangeData.GetSymbolsAsync(OKXInstrumentType.Swap).Result;`

`Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'data[0].maxIcebergSz', line 1, position 264.`

**Comment by JKorf** [comment]
Thanks for the report, fixed in latest version
