### ISSUE TITLE
GetMaximumLoanAmountAsync error

### ISSUE THREAD

**Issue by overstartup** [JKorf/OKX.Net#8]
this metthod gives error:            
`var maximumLoan = okxRestClient.UnifiedApi.Account.GetMaximumLoanAmountAsync(preOrder.Symbol, marginmode).Result;`

`{"code":"51000","data":[],"msg":"Parameter instIdBTC-USDT-SWAP error"}`

**Comment by JKorf** [comment]
The parameter should be BTC-USDT
