### ISSUE TITLE
why i get error when i send my clientOrderId in placeing order?

### ISSUE THREAD

**Issue by overstartup** [JKorf/OKX.Net#9]
i'm just sending a random client ID. do I need to set up a broker here? if you set it by some special id, please let me know how can i change it?

```
 var orderResult = await okxRestClient.UnifiedApi.Trading.PlaceOrderAsync(preOrder.Symbol, orderSide, OKXOrderType.MarketOrder, preOrder.Quantity, preOrder.PriceToBuy,
                        positionSide, trademode, clientOrderId: clientOrderId);
```

`{51000: Parameter clOrdId error }`

is "078ee129065aBCDE638315340601685538" yours:

{"clOrdId":"078ee129065aBCDE638315340601685538","instId":"BTC-USDT-SWAP","ordType":"market","posSide":"short","px":"27107.6","side":"sell","sz":"415","tag":"078ee129065aBCDE","tdMode":"cross"}

**Comment by JKorf** [comment]
BrokerId can now be set in the client options. The reason you got an error is because the total clOrdId string should be 32 characters or less.
